
# Workflow para fazer o deploy de um site estático simples para o GitHub Pages
name: Deploy Static Content to Pages

on:
  # Executa sempre que você envia código para a branch `main`
  push:
    branches: ["main"]

  # Permite que você execute este workflow manualmente na aba Actions
  workflow_dispatch:

# Define as permissões para o token do GITHUB para permitir o deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas um deploy concorrente, cancelando execuções mais antigas em andamento
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Faz o upload do diretório de build
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
